
file(GLOB SRC
  "${CMAKE_CURRENT_SOURCE_DIR}/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/SWDrivers/Src/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/SPIBus/ADC/Src/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/SPIBus/GPIO/Src/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/SPIBus/Flash/Src/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/I2CBus/Basic/Src/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/I2CBus/Sensors/Src/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/I2CBus/RTC/Src/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/I2CBus/EEPROM/Src/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/I2CBus/GPIO/Src/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/I2CBus/PMIC/Src/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/SdioBus/Cards/Src/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/EthPhy/Src/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/EthPhy/RMII/Src/*.c"
  "${CMAKE_CURRENT_SOURCE_DIR}/Proto/Src/*.c"
)

set_property(GLOBAL PROPERTY HDL_HEADERS
  "${CMAKE_CURRENT_SOURCE_DIR}/"
  "${CMAKE_CURRENT_SOURCE_DIR}/Core"
  "${CMAKE_CURRENT_SOURCE_DIR}/Ifaces"
  "${CMAKE_CURRENT_SOURCE_DIR}/SWDrivers"
  "${CMAKE_CURRENT_SOURCE_DIR}/SPIBus/ADC"
  "${CMAKE_CURRENT_SOURCE_DIR}/SPIBus/GPIO"
  "${CMAKE_CURRENT_SOURCE_DIR}/SPIBus/Flash"
  "${CMAKE_CURRENT_SOURCE_DIR}/I2CBus/Basic"
  "${CMAKE_CURRENT_SOURCE_DIR}/I2CBus/Sensors"
  "${CMAKE_CURRENT_SOURCE_DIR}/I2CBus/RTC"
  "${CMAKE_CURRENT_SOURCE_DIR}/I2CBus/EEPROM"
  "${CMAKE_CURRENT_SOURCE_DIR}/I2CBus/GPIO"
  "${CMAKE_CURRENT_SOURCE_DIR}/I2CBus/PMIC"
  "${CMAKE_CURRENT_SOURCE_DIR}/SdioBus/Cards"
  "${CMAKE_CURRENT_SOURCE_DIR}/EthPhy"
  "${CMAKE_CURRENT_SOURCE_DIR}/EthPhy/RMII"
  "${CMAKE_CURRENT_SOURCE_DIR}/Proto"
)

set_property(GLOBAL PROPERTY HDL_SOURCES ${SRC})

add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/McuPort")
