get_property(CORE GLOBAL PROPERTY CORE)
get_property(MANUFACTURER GLOBAL PROPERTY MCU_MANUFACTURER)
get_property(MCU GLOBAL PROPERTY MCU)
get_property(STACK_RESERV GLOBAL PROPERTY STACK_RESERV)
get_property(HEAP_RESERV GLOBAL PROPERTY HEAP_RESERV)
get_property(BOOT_OFFSET GLOBAL PROPERTY BOOT_OFFSET)
get_property(CUSTOM_LINKER_SCRIPT GLOBAL PROPERTY CUSTOM_LINKER_SCRIPT)

file(GLOB SRC
  "${CMAKE_CURRENT_SOURCE_DIR}/Debug/Segger_RTT/RTT/*.c"
)

set_property(GLOBAL APPEND PROPERTY HDL_HEADERS
  "${CMAKE_CURRENT_SOURCE_DIR}/Debug/Segger_RTT/RTT/"
  "${CMAKE_CURRENT_SOURCE_DIR}/Debug/Segger_RTT/Config/"
)

set_property(GLOBAL APPEND PROPERTY HDL_SOURCES ${SRC})

#Add all core dirs
add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/ARM")

#=================

get_property(CORE_SUPPORT GLOBAL PROPERTY CORE_SUPPORTED)

if(NOT CORE_SUPPORT STREQUAL "OK")
  message(SEND_ERROR "Core ${CORE} unsupported!")
endif()

get_property(MCU_SUPPORT GLOBAL PROPERTY MCU_SUPPORTED)

if(NOT MCU_SUPPORT STREQUAL "OK")
  message(SEND_ERROR "MCU ${MCU} unsupported!")
endif()

get_property(MAN_SUPPORT GLOBAL PROPERTY MANUFACTURER_SUPPORTED)

if(NOT MAN_SUPPORT STREQUAL "OK")
  message(SEND_ERROR "MCU manufacturer ${MANUFACTURER} unsupported!")
endif()

