#ifndef MIG_USPD_H_
#define MIG_USPD_H_

extern bldl_uspd_led_port_t mod_uspd_led_port1;
extern bldl_uspd_led_port_t mod_uspd_led_port2;
extern bldl_uspd_led_port_t mod_uspd_led_port3;
extern bldl_uspd_led_port_t mod_uspd_led_port4;
extern bldl_uspd_led_port_t mod_uspd_led_port5;
extern bldl_uspd_led_port_t mod_uspd_led_port6;
extern bldl_uspd_led_port_t mod_uspd_led_port7;
extern bldl_uspd_led_port_t mod_uspd_led_port8;
extern bldl_uspd_led_port_t mod_uspd_led_port9;
extern bldl_uspd_led_port_t mod_uspd_led_port10;
extern bldl_uspd_led_port_t mod_uspd_led_port11;
extern bldl_uspd_led_port_t mod_uspd_led_port12;

extern bldl_uspd_discrete_port_t mod_uspd_od_port1;
extern bldl_uspd_discrete_port_t mod_uspd_od_port2;
extern bldl_uspd_discrete_port_t mod_uspd_od_port3;
extern bldl_uspd_discrete_port_t mod_uspd_od_port4;
extern bldl_uspd_discrete_port_t mod_uspd_od_port5;
extern bldl_uspd_discrete_port_t mod_uspd_od_port6;
extern bldl_uspd_discrete_port_t mod_uspd_od_port7;
extern bldl_uspd_discrete_port_t mod_uspd_od_port8;

extern bldl_uspd_ain_port_t mod_uspd_ai_port0;
extern bldl_uspd_ain_port_t mod_uspd_ai_port1;
extern bldl_uspd_ain_port_t mod_uspd_ai_port2;
extern bldl_uspd_ain_port_t mod_uspd_ai_port3;

extern bldl_uspd_port_expander_t mod_uspd_port_expander;

#endif // MIG_USPD_H_