#ifndef MIG_USPD_H_
#define MIG_USPD_H_

extern bldl_uspd_led_port_t mod_gpio_a15_led1;
extern bldl_uspd_led_port_t mod_gpio_c10_led2;
extern bldl_uspd_led_port_t mod_gpio_c11_led3;
extern bldl_uspd_led_port_t mod_gpio_c12_led4;
extern bldl_uspd_led_port_t mod_gpio_d0_led5;
extern bldl_uspd_led_port_t mod_gpio_d1_led6;
extern bldl_uspd_led_port_t mod_gpio_d2_led7;
extern bldl_uspd_led_port_t mod_gpio_d3_led8;
extern bldl_uspd_led_port_t mod_gpio_d4_led9;
extern bldl_uspd_led_port_t mod_gpio_d5_led10;
extern bldl_uspd_led_port_t mod_gpio_d6_led11;
extern bldl_uspd_led_port_t mod_gpio_d7_led12;

extern bldl_uspd_discrete_port_t mod_uspd_od_port1;
extern bldl_uspd_discrete_port_t mod_uspd_od_port2;
extern bldl_uspd_discrete_port_t mod_uspd_od_port3;
extern bldl_uspd_discrete_port_t mod_uspd_od_port4;
extern bldl_uspd_discrete_port_t mod_uspd_od_port5;
extern bldl_uspd_discrete_port_t mod_uspd_od_port6;
extern bldl_uspd_discrete_port_t mod_uspd_od_port7;
extern bldl_uspd_discrete_port_t mod_uspd_od_port8;

extern bldl_uspd_ain_port_t mod_uspd_ai_port0;
extern bldl_uspd_ain_port_t mod_uspd_ai_port1;
extern bldl_uspd_ain_port_t mod_uspd_ai_port2;
extern bldl_uspd_ain_port_t mod_uspd_ai_port3;

#endif // MIG_USPD_H_